### ISSUE TITLE
need of X Window to access your Qt app with VNC  

### ISSUE THREAD

**Issue by pablojr** [UvinduW/Cross-Compiling-Qt-for-Raspberry-Pi-4#2]
Just one comment from your very detailed guide.

> If I boot into the desktop mode and launch the app, it will run in windowed mode. This does have the benefit of being able to VNC into the Raspberry Pi and view what the result looks like.

You can run a Qt app with `-platform vnc` argument and it'll be accesible remotely with a VNC client, without the need of having a X Window manager.

See [this post](https://jumpnowtek.com/rpi/Running-Qt5-Apps-Over-VNC.html) for more details.

Thanks.

**Comment by UvinduW** [comment]
Hi, thanks for pointing this out! I wasn't aware of this flag. I've updated the instructions with this information.
In a quick test I did, it appears that applications with OpenGL enabled don't really work in this mode as I get the following error:

`This plugin does not support createPlatformOpenGLContext!`

I guess the eglfs platform and VNC are mutually exclusive
